use_frameworks!
platform :ios, '8.0'
workspace 'Roy.xcworkspace'


target 'Roy_Example' do
  pod 'Roy', :path => '../'
#  pod 'UserPlugin', :path => './UserPlugin'
#  pod 'Platform', :path => './Platform'
#  pod 'AuthPlugin', :path => './AuthPlugin'
  pod 'SnapKit', '~> 4.0.0'
  target 'Roy_Tests' do
    inherit! :search_paths
#    pod 'UserPlugin', :path => './UserPlugin'
#    pod 'Platform', :path => './Platform'
#    pod 'AuthPlugin', :path => './AuthPlugin'
	pod 'Roy', :path => '../'
    pod 'SnapKit', '~> 4.0.0'
  end
end

