use_frameworks!
platform :ios, '8.0'
workspace 'Roy.xcworkspace'


target 'Roy_Example' do
  pod 'Roy', :path => '../'
	
  target 'Roy_Tests' do
    inherit! :search_paths


  end
end



target 'TestModule' do
    pod 'Roy', :path => '../'
    project 'TestModule/TestModule.xcodeproj'
end
